################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
OBJ_SRCS := 
C++_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
obj/local/armeabi/objs/spine_static \
obj/local/armeabi/objs/cpufeatures \
obj/local/armeabi/objs/cocostudio_static/WidgetReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/TextReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/TextFieldReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/TextBMFontReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/TextAtlasReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/SpriteReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/SliderReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/SingleNodeReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ScrollViewReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ProjectNodeReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ParticleReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/PageViewReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/NodeReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/LoadingBarReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ListViewReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/LayoutReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ImageViewReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/GameMapReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ComAudioReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/CheckBoxReader \
obj/local/armeabi/objs/cocostudio_static/WidgetReader/ButtonReader \
obj/local/armeabi/objs/cocostudio_static \
obj/local/armeabi/objs/cocostudio_static/ActionTimeline \
obj/local/armeabi/objs/cocosdenshion_static/jni \
obj/local/armeabi/objs/cocosdenshion_static \
obj/local/armeabi/objs/cocosbuilder_static \
obj/local/armeabi/objs/cocos_ui_static \
obj/local/armeabi/objs/cocos_ui_static/UIEditBox \
obj/local/armeabi/objs/cocos_network_static \
obj/local/armeabi/objs/cocos_flatbuffers_static \
obj/local/armeabi/objs/cocos_extension_static/physics-nodes \
obj/local/armeabi/objs/cocos_extension_static/assets-manager \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCScrollView \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCControlExtension \
obj/local/armeabi/objs/cocos3d_static \
obj/local/armeabi/objs/cocos2dxandroid_static/jni \
obj/local/armeabi/objs/cocos2dxandroid_static \
obj/local/armeabi/objs/cocos2dx_internal_static/renderer \
obj/local/armeabi/objs/cocos2dx_internal_static/platform \
obj/local/armeabi/objs/cocos2dx_internal_static/physics/chipmunk \
obj/local/armeabi/objs/cocos2dx_internal_static/physics \
obj/local/armeabi/objs/cocos2dx_internal_static/math \
obj/local/armeabi/objs/cocos2dx_internal_static/deprecated \
obj/local/armeabi/objs/cocos2dx_internal_static \
obj/local/armeabi/objs/cocos2dx_internal_static/base \
obj/local/armeabi/objs/cocos2dx_internal_static/__/external/xxhash \
obj/local/armeabi/objs/cocos2dx_internal_static/__/external/unzip \
obj/local/armeabi/objs/cocos2dx_internal_static/__/external/tinyxml2 \
obj/local/armeabi/objs/cocos2dx_internal_static/__/external/edtaa3func \
obj/local/armeabi/objs/cocos2dx_internal_static/__/external/ConvertUTF \
obj/local/armeabi/objs/cocos2dx_internal_static/2d \
obj/local/armeabi/objs/cocos2dcpp_shared/hellocpp \
obj/local/armeabi/objs/cocos2dcpp_shared/__/__/Classes/json \
obj/local/armeabi/objs/cocos2dcpp_shared/__/__/Classes \
obj/local/armeabi/objs/box2d_static/Rope \
obj/local/armeabi/objs/box2d_static/Dynamics \
obj/local/armeabi/objs/box2d_static/Dynamics/Joints \
obj/local/armeabi/objs/box2d_static/Dynamics/Contacts \
obj/local/armeabi/objs/box2d_static/Common \
obj/local/armeabi/objs/box2d_static/Collision \
obj/local/armeabi/objs/box2d_static/Collision/Shapes \
obj/local/armeabi/objs/audioengine_static/__ \
obj/local/armeabi/objs/audioengine_static \
jni/hellocpp \
cocos2d/plugin/protocols/platform/android \
cocos2d/plugin/protocols \
cocos2d/plugin/plugins/twitter/proj.ios/FHSTwitterEngine/OAuthConsumer/Crytpo \
cocos2d/plugin/luabindings/manual \
cocos2d/plugin/luabindings/auto \
cocos2d/plugin/jsbindings/manual \
cocos2d/plugin/jsbindings/auto \
cocos2d/external/xxtea \
cocos2d/external/xxhash \
cocos2d/external/websockets/include/wp_8.1/win32helpers \
cocos2d/external/websockets/include/wp8/win32helpers \
cocos2d/external/websockets/include/winrt_8.1/win32helpers \
cocos2d/external/unzip \
cocos2d/external/tinyxml2 \
cocos2d/external/flatbuffers \
cocos2d/external/edtaa3func \
cocos2d/external/ConvertUTF \
cocos2d/external/Box2D/Rope \
cocos2d/external/Box2D/Dynamics \
cocos2d/external/Box2D/Dynamics/Joints \
cocos2d/external/Box2D/Dynamics/Contacts \
cocos2d/external/Box2D/Common \
cocos2d/external/Box2D/Collision \
cocos2d/external/Box2D/Collision/Shapes \
cocos2d/extensions/physics-nodes \
cocos2d/extensions/assets-manager \
cocos2d/extensions/GUI/CCScrollView \
cocos2d/extensions/GUI/CCControlExtension \
cocos2d/extensions \
cocos2d/cocos/ui \
cocos2d/cocos/ui/UIEditBox \
cocos2d/cocos/storage/local-storage \
cocos2d/cocos/renderer \
cocos2d/cocos/platform/wp8-xaml/cpp \
cocos2d/cocos/platform/wp8 \
cocos2d/cocos/platform/winrt \
cocos2d/cocos/platform/win8.1-universal \
cocos2d/cocos/platform/win32 \
cocos2d/cocos/platform/linux \
cocos2d/cocos/platform/desktop \
cocos2d/cocos/platform/apple \
cocos2d/cocos/platform/android/jni \
cocos2d/cocos/platform/android \
cocos2d/cocos/platform \
cocos2d/cocos/physics/chipmunk \
cocos2d/cocos/physics \
cocos2d/cocos/network \
cocos2d/cocos/math \
cocos2d/cocos/editor-support/spine \
cocos2d/cocos/editor-support/cocostudio/WidgetReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextFieldReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextBMFontReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextAtlasReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/SpriteReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/SliderReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/SingleNodeReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ScrollViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ProjectNodeReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ParticleReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/PageViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/NodeReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/LoadingBarReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ListViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/LayoutReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ImageViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/GameMapReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ComAudioReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/CheckBoxReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ButtonReader \
cocos2d/cocos/editor-support/cocostudio \
cocos2d/cocos/editor-support/cocostudio/ActionTimeline \
cocos2d/cocos/editor-support/cocosbuilder \
cocos2d/cocos/deprecated \
cocos2d/cocos \
cocos2d/cocos/base \
cocos2d/cocos/audio/wp8 \
cocos2d/cocos/audio/winrt \
cocos2d/cocos/audio/win32 \
cocos2d/cocos/audio/openal \
cocos2d/cocos/audio/linux \
cocos2d/cocos/audio/android/jni \
cocos2d/cocos/audio/android \
cocos2d/cocos/audio \
cocos2d/cocos/3d \
cocos2d/cocos/2d \
cocos2d/build/wp8/Cocos2dShaderCompiler \
Classes/json/lib_json \
Classes/json \
Classes \

